version: '3.4'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'brewsty'
      MYSQL_ROOT_PASSWORD: 'system'

    ports:
      - '3307:3306'
    volumes:
      - brewsty-volume:/var/lib/mysql

  brewsty:
    depends_on:
      - db
    image: ${DOCKER_REGISTRY-}brewsty
    build:
      context: .
      dockerfile: Brewsty/Dockerfile

volumes:
  brewsty-volume: